### ISSUE TITLE
AssertionError: Context can only be used within the scope of a provider

### ISSUE THREAD

**Issue by sylvoslee** [stevej2608/dash-flightdeck#1]
```
Traceback (most recent call last):
  File "D:\test\dash-flightdeck\app.py", line 39, in <module>
    app = create_app(create_dash)
  File "D:\test\dash-flightdeck\app.py", line 31, in create_app
    app = dash_factory()
  File "D:\test\dash-flightdeck\app.py", line 22, in create_dash
    app = DashSPA( __name__,
  File "C:\test\lib\site-packages\dash_spa\spa_pages.py", line 125, in __init__
    super().__init__(
  File "C:\test\lib\site-packages\dash\dash.py", line 501, in __init__
    self.init_app()
  File "C:\test\lib\site-packages\dash_spa\spa_pages.py", line 134, in init_app
    super().init_app(app, **kwargs)
  File "C:\test\lib\site-packages\dash\dash.py", line 566, in init_app
    self.enable_pages()
  File "C:\test\lib\site-packages\dash\dash.py", line 2024, in enable_pages
    self._import_layouts_from_pages()
  File "C:\test\lib\site-packages\dash_spa\spa_pages.py", line 239, in _import_layouts_from_pages
    spec.loader.exec_module(page_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\test\dash-flightdeck\pages\bootstrap_tables_page.py", line 5, in <module>
    from .bootstrap_tables import table1, table2
  File "D:\test\dash-flightdeck\pages\bootstrap_tables\__init__.py", line 2, in <module>
    from .table2 import table2
  File "D:\test\dash-flightdeck\pages\bootstrap_tables\table2.py", line 53, in <module>
    table = TravelTable(
  File "C:\test\lib\site-packages\dash_spa\components\table\table_aio.py", line 39, in __init__
    state, _ = TableContext.useState(initial_state=initial_state)
  File "C:\test\lib\site-packages\dash_spa\spa_context.py", line 521, in useState
    assert self.ctx, _NO_CONTEXT_ERROR
AssertionError: Context can only be used within the scope of a provider
```

**Comment by stevej2608** [comment]
Hi @sylvoslee. I've just changed requirements.txt to use *dash-spa 1.1.3*. Can you git clone *dash-flightdeck(v 0.0.11)* again and try it again before making any of your own changes. Let me know if that's OK or still failing.

More generally, the assertion error your seeing is because an attempt has been made to access the context state outside of an active provider. See, in this example, the last call to *myButton()* will fail with an assertion error as there is no active context.

Cheers.

```
@dataclass
class ButtonState(ContextState):
    clicks: int = 1000

ButtonContext = createContext(ButtonState)

def myButton(id):
    state = ButtonContext.getState()
    btn = html.Button("Button", id=id)

    @ButtonContext.On(btn.input.n_clicks)
    def btn_click(clicks):
        log.info('btn_click()')
        state.clicks += 1

    return btn

@ButtonContext.Provider()
def active_btn1():
    state = ButtonContext.getState()
    btn = myButton('test1')
    div = html.Div(f"Button test1 pressed {state.clicks} times!", id='div')
    return html.Div([btn, div])

@ButtonContext.Provider()
def active_btn2():
    state = ButtonContext.getState()
    btn = myButton('test2')
    div = html.Div(f"Button test2 pressed {state.clicks} times!", id='div')
    return html.Div([btn, div])

# This will fail because it's not
# wrapped in context provider

asset_error_btn = myButton()

layout = html.Div([active_btn1, active_btn2])
```

**Comment by sylvoslee** [comment]
Still getting the same error

**Comment by stevej2608** [comment]
OK thanks for the report. 

I've just tried the code on Windows and I get the same error as you so that's great. I normally work in docker containers and the code runs fine so it's a bit weird. I'll look at it sometime today. Cheers.

**Comment by stevej2608** [comment]
OK fixed. The bootstrap table examples were missing @TableContext.Provider decorators. No idea why the would run OK on docker python:3.8-buster and not on Windows. 

Thanks for flagging it. Cheers.

**Comment by sylvoslee** [comment]
fixed
